import { Product } from './products-cars';

export const bicycleCategories = {
  road: 'road',
  mountain: 'mountain',
  electric: 'electric',
  commuter: 'commuter',
  folding: 'folding',
  hybrid: 'hybrid'
} as const;

// 50 different bicycle models across 6 categories
export const bicycles: Product[] = [
  // Road Bikes (12 models)
  { id: 'bike-road-001', name: 'Specialized S-Works Tarmac SL8', category: 'bicycle', type: 'road', brand: 'Specialized', model: 'S-Works Tarmac SL8', price: 89999, year: 2024, description: '顶级竞赛公路车，超轻碳纤维车架', features: ['FACT 12r碳纤维', 'Shimano Dura-Ace Di2', 'Roval Rapide CLX II', '气动优化'], specs: { 重量: '6.2kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'Roval Rapide CLX II', 车架: 'FACT 12r碳纤维' }},
  { id: 'bike-road-002', name: 'Trek Émonda SLR 9', category: 'bicycle', type: 'road', brand: 'Trek', model: 'Émonda SLR 9', price: 79999, year: 2024, description: 'Trek旗舰爬坡公路车', features: ['OCLV 800碳纤维', 'Shimano Dura-Ace Di2', 'Bontrager Aeolus RSL', 'IsoSpeed减震'], specs: { 重量: '6.5kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'Bontrager Aeolus RSL', 车架: 'OCLV 800碳纤维' }},
  { id: 'bike-road-003', name: 'Giant TCR Advanced SL 0', category: 'bicycle', type: 'road', brand: 'Giant', model: 'TCR Advanced SL 0', price: 49999, year: 2024, description: '捷安特顶级竞赛公路车', features: ['Advanced SL碳纤维', 'Shimano Dura-Ace', 'Giant SLR 1', 'Variant座舱'], specs: { 重量: '6.8kg', 变速: 'Shimano Dura-Ace 11速', 轮组: 'Giant SLR 1', 车架: 'Advanced SL碳纤维' }},
  { id: 'bike-road-004', name: 'Canyon Ultimate CF SLX 9', category: 'bicycle', type: 'road', brand: 'Canyon', model: 'Ultimate CF SLX 9', price: 42999, year: 2024, description: 'Canyon顶级全能公路车', features: ['CF SLX碳纤维', 'Shimano Dura-Ace Di2', 'DT Swiss ARC 1100', '一体式座舱'], specs: { 重量: '6.6kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'DT Swiss ARC 1100', 车架: 'CF SLX碳纤维' }},
  { id: 'bike-road-005', name: 'Pinarello Dogma F', category: 'bicycle', type: 'road', brand: 'Pinarello', model: 'Dogma F', price: 99999, year: 2024, description: '意大利顶级竞赛公路车', features: ['Torayca T1100 1K碳纤维', 'Shimano Dura-Ace Di2', 'Fulcrum Speed 55T', '非对称设计'], specs: { 重量: '6.3kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'Fulcrum Speed 55T', 车架: 'T1100 1K碳纤维' }},
  { id: 'bike-road-006', name: 'Cervélo S5', category: 'bicycle', type: 'road', brand: 'Cervélo', model: 'S5 Ultegra Di2', price: 52999, year: 2024, description: 'Cervélo气动公路车', features: ['高模量碳纤维', 'Shimano Ultegra Di2', 'Reserve 52/63', '气动优化'], specs: { 重量: '7.2kg', 变速: 'Shimano Ultegra 12速', 轮组: 'Reserve 52/63', 车架: '高模量碳纤维' }},
  { id: 'bike-road-007', name: 'Colnago V4Rs', category: 'bicycle', type: 'road', brand: 'Colnago', model: 'V4Rs Super Record', price: 119999, year: 2024, description: '意大利手工碳纤维公路车', features: ['CC.01碳纤维', 'Campagnolo Super Record EPS', 'Campagnolo Bora Ultra WTO', '意大利制造'], specs: { 重量: '6.4kg', 变速: 'Campagnolo Super Record 12速', 轮组: 'Bora Ultra WTO', 车架: 'CC.01碳纤维' }},
  { id: 'bike-road-008', name: 'BMC Teammachine SLR01', category: 'bicycle', type: 'road', brand: 'BMC', model: 'Teammachine SLR01', price: 69999, year: 2024, description: '瑞士精工公路车', features: ['Premium碳纤维', 'Shimano Dura-Ace Di2', 'DT Swiss ARC 1400', 'ICS一体座舱'], specs: { 重量: '6.7kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'DT Swiss ARC 1400', 车架: 'Premium碳纤维' }},
  { id: 'bike-road-009', name: 'Scott Addict RC Ultimate', category: 'bicycle', type: 'road', brand: 'Scott', model: 'Addict RC Ultimate', price: 64999, year: 2024, description: 'Scott轻量化公路车', features: ['HMX-SL碳纤维', 'Shimano Dura-Ace Di2', 'Syncros Capital 1.0', 'Syncros座舱'], specs: { 重量: '6.5kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'Syncros Capital 1.0', 车架: 'HMX-SL碳纤维' }},
  { id: 'bike-road-010', name: 'Bianchi Oltre RC', category: 'bicycle', type: 'road', brand: 'Bianchi', model: 'Oltre RC Dura-Ace', price: 74999, year: 2024, description: '意大利经典Celeste色公路车', features: ['Countervail碳纤维', 'Shimano Dura-Ace Di2', 'Fulcrum Racing Zero', 'CV减震技术'], specs: { 重量: '6.9kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'Fulcrum Racing Zero', 车架: 'Countervail碳纤维' }},
  { id: 'bike-road-011', name: 'Cannondale SuperSix EVO', category: 'bicycle', type: 'road', brand: 'Cannondale', model: 'SuperSix EVO Hi-MOD', price: 59999, year: 2024, description: 'Cannondale全能竞赛公路车', features: ['Hi-MOD碳纤维', 'Shimano Dura-Ace Di2', 'HollowGram 45', 'SAVE微悬架'], specs: { 重量: '6.8kg', 变速: 'Shimano Dura-Ace 12速', 轮组: 'HollowGram 45', 车架: 'Hi-MOD碳纤维' }},
  { id: 'bike-road-012', name: 'Merida Reacto Team-E', category: 'bicycle', type: 'road', brand: 'Merida', model: 'Reacto Team-E', price: 39999, year: 2024, description: '美利达气动公路车', features: ['CF5碳纤维', 'Shimano Ultegra Di2', 'Fulcrum Racing 400', '气动设计'], specs: { 重量: '7.5kg', 变速: 'Shimano Ultegra 11速', 轮组: 'Fulcrum Racing 400', 车架: 'CF5碳纤维' }},

  // Mountain Bikes (12 models)
  { id: 'bike-mtb-001', name: 'Santa Cruz Megatower', category: 'bicycle', type: 'mountain', brand: 'Santa Cruz', model: 'Megatower CC XX1 AXS', price: 89999, year: 2024, description: '顶级长行程山地车', features: ['CC碳纤维', 'SRAM XX1 AXS', 'RockShox ZEB 180mm', 'Reserve轮组'], specs: { 重量: '13.2kg', 变速: 'SRAM XX1 AXS 12速', 前叉: 'RockShox ZEB 180mm', 后避震: 'Fox Float X2 165mm' }},
  { id: 'bike-mtb-002', name: 'Specialized Stumpjumper EVO', category: 'bicycle', type: 'mountain', brand: 'Specialized', model: 'S-Works Stumpjumper EVO', price: 79999, year: 2024, description: 'Specialized全能山地车', features: ['FACT 12r碳纤维', 'SRAM X01 AXS', 'RockShox Zeb 160mm', 'Roval轮组'], specs: { 重量: '12.8kg', 变速: 'SRAM X01 AXS 12速', 前叉: 'RockShox Zeb 160mm', 后避震: 'Fox Float X 150mm' }},
  { id: 'bike-mtb-003', name: 'Trek Slash 9.9', category: 'bicycle', type: 'mountain', brand: 'Trek', model: 'Slash 9.9 XX1 AXS', price: 84999, year: 2024, description: 'Trek速降山地车', features: ['OCLV Mountain碳纤维', 'SRAM XX1 AXS', 'RockShox ZEB 180mm', 'Bontrager轮组'], specs: { 重量: '13.5kg', 变速: 'SRAM XX1 AXS 12速', 前叉: 'RockShox ZEB 180mm', 后避震: 'Fox Float X2 170mm' }},
  { id: 'bike-mtb-004', name: 'Giant Reign Advanced Pro 29', category: 'bicycle', type: 'mountain', brand: 'Giant', model: 'Reign Advanced Pro 29', price: 54999, year: 2024, description: '捷安特全地形山地车', features: ['Advanced复合碳纤维', 'SRAM GX Eagle AXS', 'Fox 38 170mm', 'Maestro悬架'], specs: { 重量: '14.2kg', 变速: 'SRAM GX Eagle AXS 12速', 前叉: 'Fox 38 170mm', 后避震: 'Fox Float X 160mm' }},
  { id: 'bike-mtb-005', name: 'Canyon Spectral CF 9', category: 'bicycle', type: 'mountain', brand: 'Canyon', model: 'Spectral CF 9', price: 49999, year: 2024, description: 'Canyon全能山地车', features: ['CF碳纤维', 'SRAM X01 Eagle', 'Fox 36 150mm', 'Shapeshifter'], specs: { 重量: '13.8kg', 变速: 'SRAM X01 Eagle 12速', 前叉: 'Fox 36 150mm', 后避震: 'Fox Float DPS 140mm' }},
  { id: 'bike-mtb-006', name: 'Yeti SB150', category: 'bicycle', type: 'mountain', brand: 'Yeti', model: 'SB150 T2', price: 94999, year: 2024, description: 'Yeti顶级Enduro山地车', features: ['Turq碳纤维', 'SRAM XX1 AXS', 'Fox 38 170mm', 'Switch Infinity'], specs: { 重量: '13.1kg', 变速: 'SRAM XX1 AXS 12速', 前叉: 'Fox 38 170mm', 后避震: 'Fox Float X2 165mm' }},
  { id: 'bike-mtb-007', name: 'Pivot Firebird 29', category: 'bicycle', type: 'mountain', brand: 'Pivot', model: 'Firebird 29 Team XX1', price: 99999, year: 2024, description: 'Pivot长行程山地车', features: ['高模量碳纤维', 'SRAM XX1 AXS', 'Fox 38 180mm', 'DW-Link'], specs: { 重量: '13.4kg', 变速: 'SRAM XX1 AXS 12速', 前叉: 'Fox 38 180mm', 后避震: 'Fox Float X2 170mm' }},
  { id: 'bike-mtb-008', name: 'Scott Ransom 900 Ultimate', category: 'bicycle', type: 'mountain', brand: 'Scott', model: 'Ransom 900 Ultimate', price: 74999, year: 2024, description: 'Scott Enduro山地车', features: ['HMX碳纤维', 'SRAM X01 AXS', 'RockShox ZEB 170mm', 'TwinLoc悬架'], specs: { 重量: '13.6kg', 变速: 'SRAM X01 AXS 12速', 前叉: 'RockShox ZEB 170mm', 后避震: 'RockShox Super Deluxe 160mm' }},
  { id: 'bike-mtb-009', name: 'Norco Range C1', category: 'bicycle', type: 'mountain', brand: 'Norco', model: 'Range C1', price: 69999, year: 2024, description: 'Norco加拿大山地车', features: ['C1碳纤维', 'SRAM X01 Eagle', 'Fox 38 170mm', 'Gravity Tune'], specs: { 重量: '14.1kg', 变速: 'SRAM X01 Eagle 12速', 前叉: 'Fox 38 170mm', 后避震: 'Fox Float X 160mm' }},
  { id: 'bike-mtb-010', name: 'Ibis Ripmo V2S', category: 'bicycle', type: 'mountain', brand: 'Ibis', model: 'Ripmo V2S XX1', price: 89999, year: 2024, description: 'Ibis全能山地车', features: ['碳纤维', 'SRAM XX1 AXS', 'Fox 36 160mm', 'DW-Link'], specs: { 重量: '13.3kg', 变速: 'SRAM XX1 AXS 12速', 前叉: 'Fox 36 160mm', 后避震: 'Fox Float X 147mm' }},
  { id: 'bike-mtb-011', name: 'Transition Sentinel Carbon', category: 'bicycle', type: 'mountain', brand: 'Transition', model: 'Sentinel Carbon GX', price: 59999, year: 2024, description: 'Transition全能山地车', features: ['碳纤维', 'SRAM GX Eagle', 'Fox 36 160mm', 'Speed Balanced Geometry'], specs: { 重量: '14.5kg', 变速: 'SRAM GX Eagle 12速', 前叉: 'Fox 36 160mm', 后避震: 'Fox Float DPX2 150mm' }},
  { id: 'bike-mtb-012', name: 'Commencal Meta AM 29', category: 'bicycle', type: 'mountain', brand: 'Commencal', model: 'Meta AM 29 Signature', price: 64999, year: 2024, description: 'Commencal法国山地车', features: ['碳纤维', 'SRAM X01 Eagle', 'RockShox Lyrik 160mm', 'Supreme悬架'], specs: { 重量: '13.9kg', 变速: 'SRAM X01 Eagle 12速', 前叉: 'RockShox Lyrik 160mm', 后避震: 'RockShox Super Deluxe 150mm' }},

  // Electric Bikes (10 models)
  { id: 'bike-ebike-001', name: 'Specialized Turbo Levo SL', category: 'bicycle', type: 'electric', brand: 'Specialized', model: 'Turbo Levo SL Expert', price: 69999, year: 2024, description: '轻量化电助力山地车', features: ['SL 1.1电机', '320Wh电池', 'FACT碳纤维', 'Mission Control APP'], specs: { 重量: '17.3kg', 电机: 'SL 1.1 240W', 电池: '320Wh', 续航: '80-120km' }},
  { id: 'bike-ebike-002', name: 'Trek Rail 9.9 XTR', category: 'bicycle', type: 'electric', brand: 'Trek', model: 'Rail 9.9 XTR', price: 89999, year: 2024, description: 'Trek顶级电助力山地车', features: ['Bosch Performance CX', '625Wh电池', 'OCLV碳纤维', 'Shimano XTR'], specs: { 重量: '22.1kg', 电机: 'Bosch CX 85Nm', 电池: '625Wh', 续航: '100-150km' }},
  { id: 'bike-ebike-003', name: 'Giant Trance X E+ Pro', category: 'bicycle', type: 'electric', brand: 'Giant', model: 'Trance X E+ Pro 29', price: 54999, year: 2024, description: '捷安特电助力山地车', features: ['SyncDrive Pro电机', '625Wh电池', 'ALUXX SL铝合金', 'RideControl APP'], specs: { 重量: '23.5kg', 电机: 'SyncDrive Pro 80Nm', 电池: '625Wh', 续航: '90-140km' }},
  { id: 'bike-ebike-004', name: 'Canyon Spectral:ON CF 9', category: 'bicycle', type: 'electric', brand: 'Canyon', model: 'Spectral:ON CF 9', price: 64999, year: 2024, description: 'Canyon电助力山地车', features: ['Shimano EP8电机', '630Wh电池', 'CF碳纤维', 'Shapeshifter'], specs: { 重量: '22.8kg', 电机: 'Shimano EP8 85Nm', 电池: '630Wh', 续航: '95-145km' }},
  { id: 'bike-ebike-005', name: 'Riese & Müller Supercharger GT', category: 'bicycle', type: 'electric', brand: 'Riese & Müller', model: 'Supercharger GT Touring', price: 59999, year: 2024, description: '德国高端电助力通勤车', features: ['Bosch Performance Line CX', '625Wh双电池', 'HS铝合金', 'Enviolo变速'], specs: { 重量: '28.5kg', 电机: 'Bosch CX 85Nm', 电池: '1250Wh', 续航: '150-220km' }},
  { id: 'bike-ebike-006', name: 'Cowboy 4', category: 'bicycle', type: 'electric', brand: 'Cowboy', model: 'Cowboy 4 ST', price: 29999, year: 2024, description: '比利时智能电助力城市车', features: ['后轮电机', '360Wh电池', '碳纤维皮带传动', 'Cowboy APP'], specs: { 重量: '18.9kg', 电机: '后轮电机 45Nm', 电池: '360Wh', 续航: '70km' }},
  { id: 'bike-ebike-007', name: 'VanMoof S5', category: 'bicycle', type: 'electric', brand: 'VanMoof', model: 'S5', price: 34999, year: 2024, description: '荷兰智能电助力城市车', features: ['前轮电机', '487Wh电池', '自动变速', '防盗追踪'], specs: { 重量: '21.0kg', 电机: '前轮电机 59Nm', 电池: '487Wh', 续航: '60-150km' }},
  { id: 'bike-ebike-008', name: 'Brompton Electric P Line', category: 'bicycle', type: 'electric', brand: 'Brompton', model: 'Electric P Line', price: 39999, year: 2024, description: '英国折叠电助力车', features: ['前轮电机', '300Wh电池', '钛合金车架', '16秒折叠'], specs: { 重量: '15.6kg', 电机: '前轮电机 250W', 电池: '300Wh', 续航: '40-80km' }},
  { id: 'bike-ebike-009', name: 'Tern Vektron S10', category: 'bicycle', type: 'electric', brand: 'Tern', model: 'Vektron S10', price: 24999, year: 2024, description: '折叠电助力通勤车', features: ['Bosch Active Line Plus', '400Wh电池', '铝合金折叠', 'Shimano Deore 10速'], specs: { 重量: '22.7kg', 电机: 'Bosch Active Plus 50Nm', 电池: '400Wh', 续航: '60-110km' }},
  { id: 'bike-ebike-010', name: 'Stromer ST7', category: 'bicycle', type: 'electric', brand: 'Stromer', model: 'ST7', price: 99999, year: 2024, description: '瑞士顶级电助力通勤车', features: ['SYNO Drive电机', '983Wh电池', '碳纤维皮带', 'Pinion变速箱'], specs: { 重量: '27.8kg', 电机: 'SYNO Drive 44Nm', 电池: '983Wh', 续航: '180km' }},

  // Commuter Bikes (8 models)
  { id: 'bike-commuter-001', name: 'Trek FX Sport Carbon 5', category: 'bicycle', type: 'commuter', brand: 'Trek', model: 'FX Sport Carbon 5', price: 19999, year: 2024, description: 'Trek碳纤维通勤车', features: ['OCLV碳纤维', 'Shimano GRX', 'IsoSpeed减震', '内走线设计'], specs: { 重量: '9.2kg', 变速: 'Shimano GRX 11速', 轮组: 'Bontrager Aeolus Elite', 车架: 'OCLV碳纤维' }},
  { id: 'bike-commuter-002', name: 'Cannondale Quick Carbon 1', category: 'bicycle', type: 'commuter', brand: 'Cannondale', model: 'Quick Carbon 1', price: 16999, year: 2024, description: 'Cannondale轻量通勤车', features: ['SmartForm碳纤维', 'Shimano Ultegra', 'SAVE微悬架', '轻量化设计'], specs: { 重量: '9.5kg', 变速: 'Shimano Ultegra 11速', 轮组: 'HollowGram', 车架: 'SmartForm碳纤维' }},
  { id: 'bike-commuter-003', name: 'Specialized Sirrus X 5.0', category: 'bicycle', type: 'commuter', brand: 'Specialized', model: 'Sirrus X 5.0', price: 14999, year: 2024, description: 'Specialized全能通勤车', features: ['FACT碳纤维', 'Shimano GRX', 'Future Shock', '多功能设计'], specs: { 重量: '10.1kg', 变速: 'Shimano GRX 11速', 轮组: 'DT Swiss', 车架: 'FACT碳纤维' }},
  { id: 'bike-commuter-004', name: 'Giant FastRoad Advanced 1', category: 'bicycle', type: 'commuter', brand: 'Giant', model: 'FastRoad Advanced 1', price: 12999, year: 2024, description: '捷安特快速通勤车', features: ['Advanced复合碳纤维', 'Shimano 105', 'D-Fuse座管', '快拆设计'], specs: { 重量: '9.8kg', 变速: 'Shimano 105 11速', 轮组: 'Giant P-R2', 车架: 'Advanced碳纤维' }},
  { id: 'bike-commuter-005', name: 'Marin Presidio 4', category: 'bicycle', type: 'commuter', brand: 'Marin', model: 'Presidio 4', price: 8999, year: 2024, description: 'Marin城市通勤车', features: ['铝合金车架', 'Shimano Deore', '内走线', '挡泥板支架'], specs: { 重量: '11.5kg', 变速: 'Shimano Deore 10速', 轮组: 'WTB', 车架: '铝合金' }},
  { id: 'bike-commuter-006', name: 'Kona Dew Plus', category: 'bicycle', type: 'commuter', brand: 'Kona', model: 'Dew Plus', price: 7999, year: 2024, description: 'Kona舒适通勤车', features: ['6061铝合金', 'Shimano Alivio', '舒适几何', '货架支架'], specs: { 重量: '12.3kg', 变速: 'Shimano Alivio 9速', 轮组: 'Alex', 车架: '6061铝合金' }},
  { id: 'bike-commuter-007', name: 'Fuji Absolute Carbon', category: 'bicycle', type: 'commuter', brand: 'Fuji', model: 'Absolute Carbon', price: 13999, year: 2024, description: 'Fuji碳纤维通勤车', features: ['C10碳纤维', 'Shimano 105', '舒适设计', '多功能'], specs: { 重量: '9.9kg', 变速: 'Shimano 105 11速', 轮组: 'Oval', 车架: 'C10碳纤维' }},
  { id: 'bike-commuter-008', name: 'Raleigh Cadent i11', category: 'bicycle', type: 'commuter', brand: 'Raleigh', model: 'Cadent i11', price: 9999, year: 2024, description: 'Raleigh内变速通勤车', features: ['铝合金车架', 'Shimano Alfine 11速', '皮带传动', '低维护'], specs: { 重量: '13.2kg', 变速: 'Shimano Alfine 11速内变', 轮组: 'Alex', 车架: '铝合金' }},

  // Folding Bikes (4 models)
  { id: 'bike-folding-001', name: 'Brompton P Line Urban', category: 'bicycle', type: 'folding', brand: 'Brompton', model: 'P Line Urban', price: 24999, year: 2024, description: '英国经典折叠车钛合金版', features: ['钛合金车架', '4档内变速', '16秒折叠', '轻量化'], specs: { 重量: '10.6kg', 变速: 'Brompton 4速', 轮径: '16英寸', 折叠尺寸: '58×56×27cm' }},
  { id: 'bike-folding-002', name: 'Dahon K3', category: 'bicycle', type: 'folding', brand: 'Dahon', model: 'K3', price: 4999, year: 2024, description: '大行超轻折叠车', features: ['铝合金车架', '3速内变', '10秒折叠', '便携设计'], specs: { 重量: '7.8kg', 变速: '3速内变', 轮径: '14英寸', 折叠尺寸: '65×28×56cm' }},
  { id: 'bike-folding-003', name: 'Tern Link D8', category: 'bicycle', type: 'folding', brand: 'Tern', model: 'Link D8', price: 6999, year: 2024, description: 'Tern经典折叠车', features: ['铝合金车架', 'Shimano 8速', 'N-Fold折叠', 'Kinetix减震'], specs: { 重量: '12.5kg', 变速: 'Shimano 8速', 轮径: '20英寸', 折叠尺寸: '79×36×72cm' }},
  { id: 'bike-folding-004', name: 'Birdy GT', category: 'bicycle', type: 'folding', brand: 'Birdy', model: 'GT', price: 19999, year: 2024, description: '德国高性能折叠车', features: ['铝合金车架', 'Shimano Deore 10速', '前后避震', '快速折叠'], specs: { 重量: '11.2kg', 变速: 'Shimano Deore 10速', 轮径: '18英寸', 折叠尺寸: '70×35×65cm' }},

  // Hybrid Bikes (4 models)
  { id: 'bike-hybrid-001', name: 'Trek Dual Sport 4', category: 'bicycle', type: 'hybrid', brand: 'Trek', model: 'Dual Sport 4', price: 9999, year: 2024, description: 'Trek多功能混合车', features: ['Alpha铝合金', 'Shimano Deore', '前避震', '多地形'], specs: { 重量: '13.2kg', 变速: 'Shimano Deore 10速', 轮组: 'Bontrager', 车架: 'Alpha铝合金' }},
  { id: 'bike-hybrid-002', name: 'Giant Roam 1 Disc', category: 'bicycle', type: 'hybrid', brand: 'Giant', model: 'Roam 1 Disc', price: 7999, year: 2024, description: '捷安特混合车', features: ['ALUXX铝合金', 'Shimano Alivio', '碟刹', '舒适几何'], specs: { 重量: '13.8kg', 变速: 'Shimano Alivio 9速', 轮组: 'Giant', 车架: 'ALUXX铝合金' }},
  { id: 'bike-hybrid-003', name: 'Specialized Crosstrail Elite', category: 'bicycle', type: 'hybrid', brand: 'Specialized', model: 'Crosstrail Elite', price: 8999, year: 2024, description: 'Specialized越野混合车', features: ['A1铝合金', 'Shimano Deore', 'SR Suntour前叉', '多功能'], specs: { 重量: '13.5kg', 变速: 'Shimano Deore 10速', 轮组: 'Specialized', 车架: 'A1铝合金' }},
  { id: 'bike-hybrid-004', name: 'Cannondale Quick CX 3', category: 'bicycle', type: 'hybrid', brand: 'Cannondale', model: 'Quick CX 3', price: 8499, year: 2024, description: 'Cannondale越野混合车', features: ['SmartForm C3铝合金', 'Shimano Acera', '前避震', 'SAVE微悬架'], specs: { 重量: '13.6kg', 变速: 'Shimano Acera 9速', 轮组: 'Maddux', 车架: 'SmartForm C3铝合金' }}
];
